// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApidocsList: typeof import('./src/components/ApidocsList.vue')['default']
    copy: typeof import('./src/components/DispatchRoute copy.vue')['default']
    DispatchRoute: typeof import('./src/components/DispatchRoute.vue')['default']
    DispatchRoutePy: typeof import('./src/components/python/DispatchRoutePy.vue')['default']
    ExamplesList: typeof import('./src/components/ExamplesList.vue')['default']
    'IEmojione:crocodile': typeof import('~icons/emojione/crocodile')['default']
    'IEva:arrowBackOutline': typeof import('~icons/eva/arrow-back-outline')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'INoto:crocodile': typeof import('~icons/noto/crocodile')['default']
    INotoV1Crocodile: typeof import('~icons/noto-v1/crocodile')['default']
    RenderDocstring: typeof import('./src/components/python/RenderDocstring.vue')['default']
    RenderMd: typeof import('./src/components/markdown/RenderMd.vue')['default']
    RenderMdPy: typeof import('./src/components/python/RenderMdPy.vue')['default']
    RenderMdPython: typeof import('./src/components/python/RenderMdPython.vue')['default']
    RenderPyDocstring: typeof import('./src/components/python/RenderPyDocstring.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaticCodeBlock: typeof import('./src/components/python/StaticCodeBlock.vue')['default']
    StaticPyCodeBlock: typeof import('./src/components/python/StaticPyCodeBlock.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}
